port: 7880

log_level: debug

rtc:
  tcp_port: 7881

  port_range_start: 50000

  port_range_end: 51000

  use_external_ip: true

  node_ip: "192.168.0.110"

redis:
  address: redis:6379

keys:
  e476ff57b4ec0ceeb83f957fce325109: nI4PoqG26z+T5vtKyB8Mc4UKEgbsiC/OE8fvQGXOTE8=
webhook:
  urls:
    - http://192.168.0.114:5005/webhook
  api_key: e476ff57b4ec0ceeb83f957fce325109