port: 7880

log_level: debug

rtc:

  tcp_port: 7881

  port_range_start: 50000

  port_range_end: 51000

  use_external_ip: true

  node_ip: "192.168.0.110"

redis:

  address: redis:6379

keys:
  262b36c27ecf06c541e4bfa1429f8015: v7omktmZC+xmQjPmchhEbWKFPyf9ZQa7IVo6xXjb4cs=
