port: 7880

log_level: debug

rtc:
  tcp_port: 7881

  port_range_start: 50000

  port_range_end: 51000

  use_external_ip: true

  node_ip: "192.168.0.110"

redis:
  address: redis:6379

keys:
  8aff81a094e2ccfc22c464273b895f3d: aHPgX+N5aiQgN8Oqe+d6PzdO409ZasLUfRgYvX+kfJk=
webhook:
  urls:
    - http://192.168.0.114:5005/webhook
  api_key: 8aff81a094e2ccfc22c464273b895f3d