services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
  livekit-server:
    image: livekit/livekit-server:latest
    restart: always
    depends_on:
      - redis
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-51000:50000-51000/udp"
    volumes:
      - ./config.yaml:/livekit-server.yaml:ro
    command: ["--config", "/livekit-server.yaml"]
  
  sip:
    image: livekit/sip
    restart: always
    depends_on:
      - redis
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-11000:10000-11000/udp"
    environment:
      SIP_CONFIG_BODY: |
        api_key: '86b965d8f5d772c96ae0172e73c95727'
        api_secret: '+iImu3nOXSya2LcS4YqzmNoNOHV4F17DelOgQIFZTD0='
        ws_url: 'ws://192.168.0.114:7880'
        redis:
          address: redis:6379
        sip_port: 5060
        rtp_port: 10000-11000
        use_external_ip: true

        logging:
          level: debug
volumes:
  redis_data:


  # sip-server:
  #   image: livekit/sip:latest
  #   ports:
  #     - "5060:5060/udp"
  #     - "5060:5060/tcp"
  #     - "10000-11000:10000-11000/udp"
  #   volumes:
  #     - ./sip-config.yaml:/sip/config.yaml
  #   depends_on:
  #     - redis