api_key: 9b5ed4546d7c0e20aeb5f4135dfd5395
api_secret: RSDwPm85rKe2sGt4RMsGNyRQjnvDeBgpkVjT/qOEaoc=
ws_url: ws://192.168.0.110:7880
redis:
  address: redis:6379
sip_port: 15060
rtp_port: 10000-11000
use_external_ip: true
logging:
  level: debug